project:
  type: website
  resources:
    - resume.pdf
    - titanic-survival.pdf
    - aws-cert-developer.pdf

website:
  title: "Data and other boring stuff"
  site-url: https://qiushiyan.dev
  open-graph:
    site-name: qiushiyan.dev
  comments:
    utterances:
      repo: qiushiyan/qiushiyan.dev
  navbar:
    right:
      - text: "Posts"
        href: posts.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/qiushiyan
format:
  html:
    theme:
      dark: [ember.scss, dark.scss]
      light: ember.scss
    css: styles.css
    citation-location: margin
    reference-location: margin
    highlight-style: pygments
    code-overflow: wrap
    fig-width: 8
    fig-height: 6
    code-link: true

comments:
  giscus:
    repo: qiushiyan/qiushiyan.dev

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    message: false
    warning: false
